export const fullWidthEntryIds: ReadonlySet<string> = new Set([
  'source-library',


  'brand-colors',
  'color-roles',
  'color-tokens',
  'state-tokens',
  'chart-palette',
  'corner-radius',
  'typography',
  'spacing',
  'shadows',
  'motion',
  'icon-registry',
  'source-icons',
  'source-artwork',
  'marketing-controls',
  'file-upload',
  'phone-number-field',
  'rich-editor',
  'banner',
  'empty-state-illustration',
  'step-indicator',
  'notification-feed',
  'prompt-area',
  'ai-sidebar',
  'sidebar',
  'accordion',
  'payment-icon',
  'table',
  'activity-feed',
  'marketing-widgets',
  'bar-chart',
  'line-chart',
  'top-n-table',
  'filter-toolbar',
  'filter-bar',
  'advanced-filter-builder',
  'filter-empty-state',
  'detail-fields-section',
  'notes-section',
  'addresses-section',
  'attachments-section',
  'cryptocurrency',
  'page',
  'section-header',
  'section-page',
  'form-header',
  'form-footer',
  'next-step-callout',
  'notification-panel',
  'schedule-view',
  'schedule-toolbar',
  'schedule-grid',
  'schedule-agenda',
  'email-threads-panel',
])

export const assetBrowserEntryIds: ReadonlySet<string> = new Set([
  'icon-registry',
  'source-icons',
  'source-artwork',
  'empty-state-illustration',
])

export const representativeVariantIds: Readonly<Record<string, string>> = {
  'ai-sidebar': 'collapsed',
  'brand-colors': 'identity',
  'state-tokens': 'info',
  'icon-registry': 'component-usage',
  'social-button': 'icon-only',
  'button-group': 'horizontal',
  'marketing-controls': 'input-filled-medium',
  'file-upload-card': 'success',
  'image-upload': 'avatar-horizontal-uploaded',
  'password-strength': 'interactive',
  'card-input': 'brand-detected',
  'color-picker': 'opacity',
  'rich-editor': 'minimal',
  'tabs': 'pill',
  'time-picker': 'inline-card',
  'banner': 'light',
  'alert': 'filled',
  'empty-state': 'source-illustration',
  'progress': 'labelled',
  'rating': 'interactive',
  'rating-bar': 'emoji-selected',
  'step-indicator': 'interactive',
  'content-label': 'avatar-40',
  'avatar': 'variants',
  'kbd': 'shortcut',
  'scroll-area': 'vertical',
  'activity-feed': 'basic',
  'kpi-card': 'suffix-and-footer',
  'sparkline': 'semantic-color',
  'line-chart': 'area',
  'pie-chart': 'donut',
  'error-message': 'with-description-action',
  'cryptocurrency': 'swap-1',
  'page': 'with-actions',
  'form-footer': 'embedded-with-delete',
  'next-step-callout': 'with-steps',
  'context-help': 'default-open',
  'notification-item': 'with-body',
}
