import './links'
import './documents'
import './versions'
import './document-crud'
import './folders'
import './shares'
import './comments'
import './templates'
import './content'
import './attachments'
import './lifecycle'
import './favorites'
import './watchers'
import './duplicate'

export { createLinkCommand, deleteLinkCommand } from './links'
export { instantiateDocumentCommand } from './documents'
export { createVersionCommand, restoreVersionCommand } from './versions'
export {
  createDocumentCommand,
  updateDocumentCommand,
  deleteDocumentCommand,
} from './document-crud'
export { createFolderCommand, updateFolderCommand, deleteFolderCommand } from './folders'
export { createShareCommand, updateShareCommand, deleteShareCommand } from './shares'
export { createCommentCommand, resolveCommentCommand } from './comments'
export { createTemplateCommand, updateTemplateCommand, deleteTemplateCommand } from './templates'
export { replaceDocumentContentCommand } from './content'
export { createDocumentAttachmentCommand, deleteDocumentAttachmentCommand } from './attachments'
export { archiveDocumentCommand, unarchiveDocumentCommand } from './lifecycle'
export { createFavoriteCommand, deleteFavoriteCommand } from './favorites'
export { createWatchCommand, deleteWatchCommand } from './watchers'
export { duplicateDocumentCommand } from './duplicate'
