import fs from 'node:fs'
import path from 'node:path'

import { addEnvValue, readEnvValue, replaceEnvLine, uncommentEnvLine, writeEnvFileText } from './env-file.mjs'
import { secretFingerprint, secretHex } from './secrets.mjs'

// Node port of the Windows launcher's Initialize-EnvFiles: fill-missing-only,
// machine-local secrets are generated once and never overwritten on re-runs.
// Postgres and superadmin credentials deliberately stay on the documented dev
// defaults (postgres/postgres, superadmin@acme.com/secret): the data volume
// outlives .env, so generated credentials drift from the volume on every
// re-clone or env regeneration, and the documented login stops working.

export function ensureEnvFiles(repoRoot, { log = console.log, warn = console.warn, extraDefaults = {} } = {}) {
  const rootEnv = path.join(repoRoot, '.env')
  const appEnvExample = path.join(repoRoot, 'apps', 'mercato', '.env.example')
  const appEnv = path.join(repoRoot, 'apps', 'mercato', '.env')

  if (!fs.existsSync(rootEnv)) {
    writeEnvFileText(rootEnv, '# Open Mercato compose environment (generated by the hybrid starter)\n')
    log(`Created ${rootEnv}`)
  }

  let jwtSecret = readEnvValue(rootEnv, 'JWT_SECRET')
  if (!jwtSecret || !jwtSecret.trim()) jwtSecret = secretHex(32)

  const setSecret = (key, value) => {
    if (addEnvValue(rootEnv, key, value)) log(`  set ${key} (${secretFingerprint(value)})`)
  }
  const setValue = (key, value) => {
    if (addEnvValue(rootEnv, key, value)) log(`  set ${key}=${value}`)
  }

  setSecret('JWT_SECRET', jwtSecret)
  setSecret('TENANT_DATA_ENCRYPTION_FALLBACK_KEY', secretHex(16))
  const meiliKey = readEnvValue(rootEnv, 'MEILISEARCH_MASTER_KEY')?.trim() || secretHex(16)
  setSecret('MEILISEARCH_MASTER_KEY', meiliKey)
  setValue('APP_URL', `http://localhost:${readEnvValue(rootEnv, 'APP_PORT')?.trim() || '3000'}`)
  setValue('OM_INIT_SUPERADMIN_EMAIL', 'superadmin@acme.com')
  for (const [key, value] of Object.entries(extraDefaults)) {
    setValue(key, value)
  }
  // Dev-default credentials, not secrets (see header). Set after extraDefaults
  // so a company preset — like anything already in .env — wins.
  setValue('OM_INIT_SUPERADMIN_PASSWORD', 'secret')
  const postgresPassword = readEnvValue(rootEnv, 'POSTGRES_PASSWORD')?.trim() || 'postgres'
  setValue('POSTGRES_PASSWORD', postgresPassword)
  // NOTE: MCP_SERVER_API_KEY is intentionally NOT generated here. `yarn dev`
  // provisions a real DB-backed key into .mercato/mcp-shared; a random env
  // value would shadow it and break OpenCode -> MCP authentication.

  if (!fs.existsSync(appEnv)) {
    if (fs.existsSync(appEnvExample)) {
      let content = fs.readFileSync(appEnvExample, 'utf8')
      content = replaceEnvLine(content, 'JWT_SECRET', jwtSecret)
      content = replaceEnvLine(content, 'AUTH_SECRET', secretHex(32))
      content = replaceEnvLine(content, 'LOOKUP_HASH_PEPPER', secretHex(16))
      // 127.0.0.1, never `localhost`: on modern Windows localhost resolves
      // to ::1 first while the published container ports listen on IPv4.
      content = replaceEnvLine(
        content,
        'DATABASE_URL',
        `postgres://postgres:${postgresPassword}@127.0.0.1:5432/open-mercato`,
      )
      // The hybrid starter runs a meilisearch container, so point the app at it
      // (the example ships these commented out).
      content = uncommentEnvLine(content, 'MEILISEARCH_HOST', 'http://127.0.0.1:7700')
      content = uncommentEnvLine(content, 'MEILISEARCH_API_KEY', meiliKey)
      writeEnvFileText(appEnv, content)
      log(`Created ${appEnv} from .env.example (placeholder secrets replaced)`)
    } else {
      warn('apps/mercato/.env.example not found; skipping app .env creation')
    }
  } else {
    log('apps/mercato/.env already exists (left untouched)')
  }

  // The host-run `mercato` CLI (yarn initialize, yarn ... mcp:ensure-api-key)
  // loads apps/mercato/.env, NOT the root compose .env. The superadmin
  // identity must live there too: otherwise `initialize` seeds one admin while
  // MCP key provisioning resolves a different (default) owner, throws "owner
  // not found", and OpenCode never gets a key. Propagate the same values
  // (fill-missing-only, so a user's own app .env is never clobbered).
  if (fs.existsSync(appEnv)) {
    const superEmail = readEnvValue(rootEnv, 'OM_INIT_SUPERADMIN_EMAIL')?.trim()
    const superPassword = readEnvValue(rootEnv, 'OM_INIT_SUPERADMIN_PASSWORD')?.trim()
    if (superEmail && addEnvValue(appEnv, 'OM_INIT_SUPERADMIN_EMAIL', superEmail)) {
      log('  set OM_INIT_SUPERADMIN_EMAIL in apps/mercato/.env')
    }
    if (superPassword && addEnvValue(appEnv, 'OM_INIT_SUPERADMIN_PASSWORD', superPassword)) {
      log('  set OM_INIT_SUPERADMIN_PASSWORD in apps/mercato/.env')
    }
  }

  return { rootEnv, appEnv, jwtSecret }
}
