import fs from 'node:fs'
import os from 'node:os'
import path from 'node:path'
import type { ModuleScanContext } from '../extension'
import { createAgentFilesExtension } from '../extensions/agent-files'

/**
 * Build a fake repo root with `docker/opencode` + `packages` markers (so the
 * extension's `findRepoRoot` resolves it) and a module whose `agents/<id>/`
 * fixture lives under `appBase`.
 */
function makeRepoFixture(): { repoRoot: string; appBase: string; pkgBase: string } {
  const repoRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'agent-files-repo-'))
  fs.mkdirSync(path.join(repoRoot, 'docker', 'opencode'), { recursive: true })
  fs.mkdirSync(path.join(repoRoot, 'packages'), { recursive: true })

  const appBase = path.join(repoRoot, 'apps', 'mercato', 'src', 'modules', 'agent_examples')
  const pkgBase = path.join(repoRoot, 'packages', 'core', 'src', 'modules', 'agent_examples')
  const agentDir = path.join(appBase, 'agents', 'deals_health_check')
  fs.mkdirSync(agentDir, { recursive: true })

  fs.writeFileSync(
    path.join(agentDir, 'AGENT.md'),
    [
      '---',
      'id: deals.health_check',
      'label: Deal health check',
      'description: Assess a deal.',
      'maxSteps: 12',
      '---',
      'You assess a deal.',
    ].join('\n'),
    'utf8',
  )
  fs.writeFileSync(
    path.join(agentDir, 'OUTCOME.md'),
    [
      '---',
      'kind: proposal',
      '---',
      '```json',
      JSON.stringify({
        type: 'object',
        required: ['confidence'],
        properties: { confidence: { type: 'number', minimum: 0, maximum: 1 } },
      }),
      '```',
    ].join('\n'),
    'utf8',
  )

  return { repoRoot, appBase, pkgBase }
}

function createScanContext(moduleId: string, appBase: string, pkgBase: string): ModuleScanContext {
  return {
    moduleId,
    roots: { appBase, pkgBase },
    imps: { appBase: `@/modules/${moduleId}`, pkgBase: `@open-mercato/core/modules/${moduleId}` },
    importIdRef: { value: 0 },
    sharedImports: [],
    resolveModuleFile: (() => null) as ModuleScanContext['resolveModuleFile'],
    resolveFirstModuleFile: (() => null) as ModuleScanContext['resolveFirstModuleFile'],
    processStandaloneConfig: () => null,
    sanitizeGeneratedModuleSpecifier: (importPath) => importPath,
  }
}

describe('createAgentFilesExtension', () => {
  let repoRoot = ''
  afterEach(() => {
    if (repoRoot) fs.rmSync(repoRoot, { recursive: true, force: true })
    repoRoot = ''
  })

  it('discovers agents/<id>/ and emits the manifest + docker agent file', () => {
    const fixture = makeRepoFixture()
    repoRoot = fixture.repoRoot

    const extension = createAgentFilesExtension()
    expect(extension.id).toBe('registry.agent-files')

    extension.scanModule(createScanContext('agent_examples', fixture.appBase, fixture.pkgBase))
    const output = extension.generateOutput()
    expect(output.size).toBe(0)

    const manifestPath = path.join(
      repoRoot,
      'packages/enterprise/src/modules/agent_orchestrator/generated/file-agents.generated.ts',
    )
    expect(fs.existsSync(manifestPath)).toBe(true)
    const manifest = fs.readFileSync(manifestPath, 'utf8')
    expect(manifest).toContain('AUTO-GENERATED by mercato generate registry')
    expect(manifest).toContain("id: \"deals.health_check\"")
    expect(manifest).toContain("openCodeAgentName: \"deals_health_check\"")
    expect(manifest).toContain('export const fileAgentDescriptors')

    const dockerFile = path.join(repoRoot, 'docker/opencode/agents/deals_health_check.md')
    expect(fs.existsSync(dockerFile)).toBe(true)
    const dockerContent = fs.readFileSync(dockerFile, 'utf8')
    expect(dockerContent).toContain('mode: primary')
    expect(dockerContent).toContain('open-mercato_agent_orchestrator_submit_outcome')
    expect(dockerContent).toContain('write: deny')
    // No sub-agents declared → `task` denied and no delegate tool (unchanged).
    expect(dockerContent).toContain('task: deny')
    expect(dockerContent).not.toContain('delegate_agent')
  })

  it('routes file-agent delegation through delegate_agent instead of the task tool', () => {
    const fixture = makeRepoFixture()
    repoRoot = fixture.repoRoot
    const agentDir = path.join(fixture.appBase, 'agents', 'deals_health_check')

    // Declare a sub-agent under sub-agents/<subid>/ (researcher + non-delegating).
    fs.writeFileSync(
      path.join(agentDir, 'AGENT.md'),
      [
        '---',
        'id: deals.health_check',
        'label: Deal health check',
        'description: Assess a deal.',
        '---',
        'You assess a deal.',
      ].join('\n'),
      'utf8',
    )
    const subDir = path.join(agentDir, 'sub-agents', 'company_researcher')
    fs.mkdirSync(subDir, { recursive: true })
    fs.writeFileSync(
      path.join(subDir, 'AGENT.md'),
      [
        '---',
        'id: deals.company_researcher',
        'label: Company researcher',
        'description: Research a company.',
        '---',
        'You research a company.',
      ].join('\n'),
      'utf8',
    )
    fs.writeFileSync(
      path.join(subDir, 'OUTCOME.md'),
      [
        '---',
        'kind: research',
        '---',
        '```json',
        JSON.stringify({ type: 'object', properties: { summary: { type: 'string' } } }),
        '```',
      ].join('\n'),
      'utf8',
    )

    const extension = createAgentFilesExtension()
    extension.scanModule(createScanContext('agent_examples', fixture.appBase, fixture.pkgBase))
    extension.generateOutput()

    const primary = fs.readFileSync(
      path.join(repoRoot, 'docker/opencode/agents/deals_health_check.md'),
      'utf8',
    )
    // The orchestrator gains the delegate_agent MCP tool, denies `task`, and
    // never grants the built-in task tool.
    expect(primary).toContain('open-mercato_agent_orchestrator_delegate_agent')
    expect(primary).toContain('task: deny')
    expect(primary).not.toContain('"task": true')
    // The prompt delegates through delegate_agent (not `task`) using the FULL
    // sub-agent id.
    expect(primary).toContain('## Sub-agents')
    expect(primary).toContain('delegate_agent')
    expect(primary).toContain('deals.company_researcher')
    expect(primary).not.toContain('by calling the `task` tool')

    // The sub-agent file gets neither the delegate tool nor `task` (depth cap = 1).
    const sub = fs.readFileSync(
      path.join(repoRoot, 'docker/opencode/agents/deals_company_researcher.md'),
      'utf8',
    )
    expect(sub).toContain('mode: subagent')
    expect(sub).toContain('task: deny')
    expect(sub).not.toContain('delegate_agent')
  })

  it('emits an agent SAMPLE.json into the manifest as sampleInput', () => {
    const fixture = makeRepoFixture()
    repoRoot = fixture.repoRoot
    const agentDir = path.join(fixture.appBase, 'agents', 'deals_health_check')
    fs.writeFileSync(
      path.join(agentDir, 'SAMPLE.json'),
      JSON.stringify({ deal: { id: 'demo-deal-1', stage: 'Proposal' } }),
      'utf8',
    )

    const extension = createAgentFilesExtension()
    extension.scanModule(createScanContext('agent_examples', fixture.appBase, fixture.pkgBase))
    extension.generateOutput()

    const manifest = fs.readFileSync(
      path.join(repoRoot, 'packages/enterprise/src/modules/agent_orchestrator/generated/file-agents.generated.ts'),
      'utf8',
    )
    expect(manifest).toContain('sampleInput: {"deal":{"id":"demo-deal-1","stage":"Proposal"}}')
  })

  it('fails generation on a malformed SAMPLE.json', () => {
    const fixture = makeRepoFixture()
    repoRoot = fixture.repoRoot
    const agentDir = path.join(fixture.appBase, 'agents', 'deals_health_check')
    fs.writeFileSync(path.join(agentDir, 'SAMPLE.json'), '{ not valid json', 'utf8')

    const extension = createAgentFilesExtension()
    expect(() =>
      extension.scanModule(createScanContext('agent_examples', fixture.appBase, fixture.pkgBase)),
    ).toThrow(/malformed SAMPLE\.json/)
  })

  it('emits an agent FACTS.json into the manifest as facts', () => {
    const fixture = makeRepoFixture()
    repoRoot = fixture.repoRoot
    const agentDir = path.join(fixture.appBase, 'agents', 'deals_health_check')
    fs.writeFileSync(
      path.join(agentDir, 'FACTS.json'),
      JSON.stringify({
        facts: [
          { label: 'Stage', source: 'input', path: 'deal.stage' },
          { label: 'Confidence', source: 'payload', path: 'confidence', format: 'percent' },
        ],
      }),
      'utf8',
    )

    const extension = createAgentFilesExtension()
    extension.scanModule(createScanContext('agent_examples', fixture.appBase, fixture.pkgBase))
    extension.generateOutput()

    const manifest = fs.readFileSync(
      path.join(repoRoot, 'packages/enterprise/src/modules/agent_orchestrator/generated/file-agents.generated.ts'),
      'utf8',
    )
    expect(manifest).toContain(
      'facts: [{"label":"Stage","source":"input","path":"deal.stage"},{"label":"Confidence","source":"payload","path":"confidence","format":"percent"}]',
    )
    expect(manifest).toContain('export type FileAgentFact')
  })

  it('fails generation on a FACTS.json entry missing label/source/path', () => {
    const fixture = makeRepoFixture()
    repoRoot = fixture.repoRoot
    const agentDir = path.join(fixture.appBase, 'agents', 'deals_health_check')
    fs.writeFileSync(
      path.join(agentDir, 'FACTS.json'),
      JSON.stringify({ facts: [{ label: 'Stage', source: 'nowhere', path: 'deal.stage' }] }),
      'utf8',
    )

    const extension = createAgentFilesExtension()
    expect(() =>
      extension.scanModule(createScanContext('agent_examples', fixture.appBase, fixture.pkgBase)),
    ).toThrow(/malformed FACTS\.json/)
  })

  it('fails generation on a malformed agent dir (missing OUTCOME.md)', () => {
    const fixture = makeRepoFixture()
    repoRoot = fixture.repoRoot
    // Remove OUTCOME.md to make the dir malformed.
    fs.rmSync(path.join(fixture.appBase, 'agents', 'deals_health_check', 'OUTCOME.md'))

    const extension = createAgentFilesExtension()
    expect(() =>
      extension.scanModule(createScanContext('agent_examples', fixture.appBase, fixture.pkgBase)),
    ).toThrow(/malformed file agent/)
  })

  it('emits native SKILL.md, unions skill tools, and writes skillsContent to the manifest', () => {
    const fixture = makeRepoFixture()
    repoRoot = fixture.repoRoot
    const agentDir = path.join(fixture.appBase, 'agents', 'deals_health_check')

    // Reference a skill in AGENT.md and author it under skills/<skill_id>/.
    fs.writeFileSync(
      path.join(agentDir, 'AGENT.md'),
      [
        '---',
        'id: deals.health_check',
        'label: Deal health check',
        'description: Assess a deal.',
        'skills: [stage_playbook]',
        'tools: [customers.get_deal]',
        '---',
        'You assess a deal.',
      ].join('\n'),
      'utf8',
    )
    const skillDir = path.join(agentDir, 'skills', 'stage_playbook')
    fs.mkdirSync(path.join(skillDir, 'examples'), { recursive: true })
    fs.writeFileSync(
      path.join(skillDir, 'SKILL.md'),
      [
        '---',
        'id: stage_playbook',
        'label: Stage playbook',
        'description: Pick the next stage.',
        'tools: [customers.analyze_deals]',
        '---',
        'STAGE_PLAYBOOK_BODY',
      ].join('\n'),
      'utf8',
    )
    fs.writeFileSync(path.join(skillDir, 'TEMPLATE.md'), 'TEMPLATE_BODY', 'utf8')
    fs.writeFileSync(path.join(skillDir, 'examples', 'a.md'), 'EXAMPLE_ONE', 'utf8')

    const extension = createAgentFilesExtension()
    extension.scanModule(createScanContext('agent_examples', fixture.appBase, fixture.pkgBase))
    extension.generateOutput()

    // Native OpenCode skill file (sanitized dir name: stage_playbook → stage-playbook).
    const nativeSkill = path.join(repoRoot, 'docker/opencode/skills/stage-playbook/SKILL.md')
    expect(fs.existsSync(nativeSkill)).toBe(true)
    const nativeContent = fs.readFileSync(nativeSkill, 'utf8')
    expect(nativeContent).toContain('name: stage-playbook')
    expect(nativeContent).toContain('STAGE_PLAYBOOK_BODY')

    // Manifest carries skillsContent and the unioned tool allowlist.
    const manifest = fs.readFileSync(
      path.join(repoRoot, 'packages/enterprise/src/modules/agent_orchestrator/generated/file-agents.generated.ts'),
      'utf8',
    )
    expect(manifest).toContain('skillsContent')
    expect(manifest).toContain('STAGE_PLAYBOOK_BODY')
    expect(manifest).toContain('TEMPLATE_BODY')
    expect(manifest).toContain('EXAMPLE_ONE')
    expect(manifest).toContain('customers.analyze_deals')

    // The docker agent file's tools block includes the skill tool too.
    const dockerAgent = fs.readFileSync(
      path.join(repoRoot, 'docker/opencode/agents/deals_health_check.md'),
      'utf8',
    )
    // Declared OM tool ids are mapped to OpenCode's MCP tool id form in the allowlist.
    expect(dockerAgent).toContain('open-mercato_customers_analyze_deals')
  })

  it('fails generation on a malformed SKILL.md (no frontmatter)', () => {
    const fixture = makeRepoFixture()
    repoRoot = fixture.repoRoot
    const agentDir = path.join(fixture.appBase, 'agents', 'deals_health_check')
    fs.writeFileSync(
      path.join(agentDir, 'AGENT.md'),
      [
        '---',
        'id: deals.health_check',
        'label: Deal health check',
        'description: Assess a deal.',
        'skills: [stage_playbook]',
        '---',
        'You assess a deal.',
      ].join('\n'),
      'utf8',
    )
    const skillDir = path.join(agentDir, 'skills', 'stage_playbook')
    fs.mkdirSync(skillDir, { recursive: true })
    fs.writeFileSync(path.join(skillDir, 'SKILL.md'), 'no frontmatter at all', 'utf8')

    const extension = createAgentFilesExtension()
    expect(() =>
      extension.scanModule(createScanContext('agent_examples', fixture.appBase, fixture.pkgBase)),
    ).toThrow(/malformed SKILL\.md/)
  })

  it('fails generation when an OUTCOME.md schema is outside the supported subset (M2)', () => {
    const fixture = makeRepoFixture()
    const agentDir = path.join(fixture.appBase, 'agents', 'deals_health_check')
    // `oneOf` parses as valid JSON but cannot compile to Zod — must fail at scan,
    // not silently parse and get dropped at load.
    fs.writeFileSync(
      path.join(agentDir, 'OUTCOME.md'),
      [
        '---',
        'kind: proposal',
        '---',
        '```json',
        JSON.stringify({ type: 'object', properties: { x: { oneOf: [{ type: 'string' }] } } }),
        '```',
      ].join('\n'),
      'utf8',
    )
    const extension = createAgentFilesExtension()
    expect(() =>
      extension.scanModule(createScanContext('agent_examples', fixture.appBase, fixture.pkgBase)),
    ).toThrow(/unsupported keyword "oneOf"/)
  })

  it('fails generation when an OUTCOME.md schema node has no supported type (M2)', () => {
    const fixture = makeRepoFixture()
    const agentDir = path.join(fixture.appBase, 'agents', 'deals_health_check')
    fs.writeFileSync(
      path.join(agentDir, 'OUTCOME.md'),
      [
        '---',
        'kind: research',
        '---',
        '```json',
        JSON.stringify({ type: 'object', properties: { x: { minimum: 0 } } }),
        '```',
      ].join('\n'),
      'utf8',
    )
    const extension = createAgentFilesExtension()
    expect(() =>
      extension.scanModule(createScanContext('agent_examples', fixture.appBase, fixture.pkgBase)),
    ).toThrow(/missing\/unsupported "type"/)
  })

  it('keeps committed agent artifacts when neither the orchestrator nor an agent module is enabled', () => {
    const fixture = makeRepoFixture()
    repoRoot = fixture.repoRoot
    const manifestPath = path.join(
      repoRoot,
      'packages/enterprise/src/modules/agent_orchestrator/generated/file-agents.generated.ts',
    )
    const dockerFile = path.join(repoRoot, 'docker/opencode/agents/deals_health_check.md')
    const skillFile = path.join(repoRoot, 'docker/opencode/skills/stage-playbook/SKILL.md')
    fs.mkdirSync(path.dirname(manifestPath), { recursive: true })
    fs.mkdirSync(path.dirname(dockerFile), { recursive: true })
    fs.mkdirSync(path.dirname(skillFile), { recursive: true })
    fs.writeFileSync(manifestPath, 'committed manifest', 'utf8')
    fs.writeFileSync(dockerFile, 'committed agent file', 'utf8')
    fs.writeFileSync(skillFile, 'committed skill file', 'utf8')

    const extension = createAgentFilesExtension()
    // A module with no `agents/` tree, standing in for a run with the
    // enterprise agents flag off.
    const otherBase = path.join(repoRoot, 'packages', 'core', 'src', 'modules', 'customers')
    fs.mkdirSync(otherBase, { recursive: true })
    extension.scanModule(createScanContext('customers', otherBase, otherBase))
    extension.generateOutput()

    expect(fs.readFileSync(manifestPath, 'utf8')).toBe('committed manifest')
    expect(fs.readFileSync(dockerFile, 'utf8')).toBe('committed agent file')
    expect(fs.readFileSync(skillFile, 'utf8')).toBe('committed skill file')
  })

  it('still prunes stale artifacts when the orchestrator is enabled without any agent', () => {
    const fixture = makeRepoFixture()
    repoRoot = fixture.repoRoot
    const dockerFile = path.join(repoRoot, 'docker/opencode/agents/deals_health_check.md')
    const skillDir = path.join(repoRoot, 'docker/opencode/skills/stage-playbook')
    fs.mkdirSync(path.dirname(dockerFile), { recursive: true })
    fs.mkdirSync(skillDir, { recursive: true })
    fs.writeFileSync(dockerFile, 'stale agent file', 'utf8')
    fs.writeFileSync(path.join(skillDir, 'SKILL.md'), 'stale skill file', 'utf8')

    const extension = createAgentFilesExtension()
    const orchestratorBase = path.join(
      repoRoot,
      'packages',
      'enterprise',
      'src',
      'modules',
      'agent_orchestrator',
    )
    fs.mkdirSync(orchestratorBase, { recursive: true })
    extension.scanModule(createScanContext('agent_orchestrator', orchestratorBase, orchestratorBase))
    extension.generateOutput()

    expect(fs.existsSync(dockerFile)).toBe(false)
    expect(fs.existsSync(skillDir)).toBe(false)
    const manifest = fs.readFileSync(
      path.join(
        repoRoot,
        'packages/enterprise/src/modules/agent_orchestrator/generated/file-agents.generated.ts',
      ),
      'utf8',
    )
    expect(manifest).toContain('export const fileAgentDescriptors: FileAgentDescriptor[] = []')
  })

  describe('standalone app layout', () => {
    /**
     * A scaffolded app has no `packages/` tree and no `docker/opencode/` before
     * the first generate, so the legacy `findRepoRoot` walk-up could never
     * resolve and the extension silently emitted nothing. With a resolver
     * reporting `isMonorepo() === false` the artifacts land in the app instead.
     */
    function makeStandaloneFixture(): { appDir: string; appBase: string; pkgBase: string } {
      const appDir = fs.mkdtempSync(path.join(os.tmpdir(), 'agent-files-standalone-'))
      const appBase = path.join(appDir, 'src', 'modules', 'agent_examples')
      const pkgBase = path.join(
        appDir,
        'node_modules',
        '@open-mercato',
        'enterprise',
        'dist',
        'modules',
        'agent_examples',
      )
      const agentDir = path.join(appBase, 'agents', 'deals_health_check')
      fs.mkdirSync(agentDir, { recursive: true })
      fs.writeFileSync(
        path.join(agentDir, 'AGENT.md'),
        [
          '---',
          'id: deals.health_check',
          'label: Deal health check',
          'description: Assess a deal.',
          '---',
          'You assess a deal.',
        ].join('\n'),
        'utf8',
      )
      fs.writeFileSync(
        path.join(agentDir, 'OUTCOME.md'),
        [
          '---',
          'kind: proposal',
          '---',
          '```json',
          JSON.stringify({
            type: 'object',
            required: ['confidence'],
            properties: { confidence: { type: 'number' } },
          }),
          '```',
        ].join('\n'),
        'utf8',
      )
      return { appDir, appBase, pkgBase }
    }

    function standaloneResolver(appDir: string) {
      return {
        isMonorepo: () => false,
        getRootDir: () => appDir,
        getAppDir: () => appDir,
        getOutputDir: () => path.join(appDir, '.mercato', 'generated'),
      }
    }

    let appDir = ''
    afterEach(() => {
      if (appDir) fs.rmSync(appDir, { recursive: true, force: true })
      appDir = ''
    })

    it('writes the manifest to .mercato/generated and agents under the app docker/ dir', () => {
      const fixture = makeStandaloneFixture()
      appDir = fixture.appDir

      const extension = createAgentFilesExtension(standaloneResolver(fixture.appDir))
      extension.scanModule(createScanContext('agent_examples', fixture.appBase, fixture.pkgBase))
      extension.generateOutput()

      // The manifest lands in the generated output dir that
      // `findGeneratedFile()` probes as `<cwd>/.mercato/generated/<file>`.
      const manifestPath = path.join(
        fixture.appDir,
        '.mercato',
        'generated',
        'file-agents.generated.ts',
      )
      expect(fs.existsSync(manifestPath)).toBe(true)
      expect(fs.readFileSync(manifestPath, 'utf8')).toContain('id: "deals.health_check"')

      // It must NOT write into node_modules, which yarn install rewrites.
      expect(
        fs.existsSync(path.join(fixture.appDir, 'node_modules', '@open-mercato', 'enterprise', 'src')),
      ).toBe(false)

      const dockerFile = path.join(
        fixture.appDir,
        'docker',
        'opencode',
        'agents',
        'deals_health_check.md',
      )
      expect(fs.existsSync(dockerFile)).toBe(true)
      expect(fs.readFileSync(dockerFile, 'utf8')).toContain('mode: primary')
    })

    it('warns instead of silently dropping agents when no output root resolves', () => {
      const fixture = makeStandaloneFixture()
      appDir = fixture.appDir
      const warn = jest.spyOn(console, 'warn').mockImplementation(() => {})

      // No resolver AND no in-repo markers: the legacy walk-up returns null.
      const extension = createAgentFilesExtension()
      extension.scanModule(createScanContext('agent_examples', fixture.appBase, fixture.pkgBase))
      const output = extension.generateOutput()

      expect(output.size).toBe(0)
      expect(warn).toHaveBeenCalledWith(expect.stringContaining('Could not resolve an output root'))
      warn.mockRestore()
    })
  })
})
