/**
 * Contract tests for `renderBootstrapRegistrationsFile`, the emitter behind
 * `bootstrap-registrations.generated.ts`.
 *
 * The file is always written — even when no generator plugin contributes a bootstrap
 * registration — so `bootstrap.ts` can import it unconditionally. These tests cover
 * that core-only case, one plugin, two plugins whose registration imports overlap
 * (de-duplication), and a malformed import statement, which must fail at generation
 * time with the offending statement named rather than emit a broken file.
 */
import ts from 'typescript-js'
import { renderBootstrapRegistrationsFile } from '../module-registry'

const CORE_ENTRY_IMPORTS = [
  'import { backendRoutes } from "./backend-routes.generated"',
  'import { frontendRoutes } from "./frontend-routes.generated"',
]
const CORE_REGISTRATION_IMPORTS = [
  "import { registerBackendRouteManifests, registerFrontendRouteManifests } from '@open-mercato/shared/modules/registry'",
]
const CORE_CALLS = [
  'registerBackendRouteManifests(backendRoutes)',
  'registerFrontendRouteManifests(frontendRoutes)',
]

function parseFile(content: string): ts.SourceFile {
  return ts.createSourceFile('bootstrap-registrations.generated.ts', content, ts.ScriptTarget.Latest, true, ts.ScriptKind.TS)
}

function expectNoSyntaxErrors(content: string): void {
  const sourceFile = parseFile(content)
  const diagnostics = (sourceFile as unknown as { parseDiagnostics?: ts.Diagnostic[] }).parseDiagnostics ?? []
  expect(diagnostics.map((diagnostic) => ts.flattenDiagnosticMessageText(diagnostic.messageText, ' '))).toEqual([])
}

function parseImports(content: string): Array<{ moduleSpecifier: string; names: string[] }> {
  return parseFile(content)
    .statements.filter(ts.isImportDeclaration)
    .map((declaration) => {
      const bindings = declaration.importClause?.namedBindings
      return {
        moduleSpecifier: (declaration.moduleSpecifier as ts.StringLiteral).text,
        names: bindings && ts.isNamedImports(bindings) ? bindings.elements.map((element) => element.name.text) : [],
      }
    })
}

function parseRegistrationCalls(content: string): string[] {
  const sourceFile = parseFile(content)
  const declaration = sourceFile.statements.find(
    (statement): statement is ts.FunctionDeclaration =>
      ts.isFunctionDeclaration(statement) && statement.name?.text === 'runBootstrapRegistrations',
  )
  if (!declaration) throw new Error('runBootstrapRegistrations declaration not found')
  return (declaration.body?.statements ?? []).map((statement) => statement.getText(sourceFile).replace(/;$/, ''))
}

function isExportedVoidFunction(content: string): boolean {
  const declaration = parseFile(content).statements.find(
    (statement): statement is ts.FunctionDeclaration =>
      ts.isFunctionDeclaration(statement) && statement.name?.text === 'runBootstrapRegistrations',
  )
  if (!declaration) return false
  const isExported = declaration.modifiers?.some((modifier) => modifier.kind === ts.SyntaxKind.ExportKeyword) ?? false
  return isExported && declaration.type?.kind === ts.SyntaxKind.VoidKeyword
}

describe('renderBootstrapRegistrationsFile', () => {
  it('emits the core route registrations when no plugin contributes one', () => {
    const content = renderBootstrapRegistrationsFile({
      entryImports: CORE_ENTRY_IMPORTS,
      registrationImports: CORE_REGISTRATION_IMPORTS,
      calls: CORE_CALLS,
    })

    expectNoSyntaxErrors(content)
    expect(content.startsWith('// AUTO-GENERATED by mercato generate registry\n')).toBe(true)
    expect(isExportedVoidFunction(content)).toBe(true)
    expect(parseImports(content)).toEqual([
      { moduleSpecifier: './backend-routes.generated', names: ['backendRoutes'] },
      { moduleSpecifier: './frontend-routes.generated', names: ['frontendRoutes'] },
      {
        moduleSpecifier: '@open-mercato/shared/modules/registry',
        names: ['registerBackendRouteManifests', 'registerFrontendRouteManifests'],
      },
    ])
    expect(parseRegistrationCalls(content)).toEqual(CORE_CALLS)
  })

  it('appends a single plugin registration after the core ones', () => {
    const content = renderBootstrapRegistrationsFile({
      entryImports: [
        ...CORE_ENTRY_IMPORTS,
        'import { securityMfaProviderEntries } from "./security-mfa-providers.generated"',
      ],
      registrationImports: [
        ...CORE_REGISTRATION_IMPORTS,
        "import { registerMfaProviders } from '@open-mercato/core/modules/security/mfa'",
      ],
      calls: [...CORE_CALLS, 'registerMfaProviders(securityMfaProviderEntries)'],
    })

    expectNoSyntaxErrors(content)
    expect(parseImports(content).map((parsed) => parsed.moduleSpecifier)).toEqual([
      './backend-routes.generated',
      './frontend-routes.generated',
      './security-mfa-providers.generated',
      '@open-mercato/shared/modules/registry',
      '@open-mercato/core/modules/security/mfa',
    ])
    expect(parseRegistrationCalls(content)).toEqual([
      ...CORE_CALLS,
      'registerMfaProviders(securityMfaProviderEntries)',
    ])
  })

  it('de-duplicates an identical registration import contributed by two plugins', () => {
    const sharedRegistrationImport = "import { registerEntries } from '@open-mercato/core/modules/shared/registrations'"
    const content = renderBootstrapRegistrationsFile({
      entryImports: [
        ...CORE_ENTRY_IMPORTS,
        'import { firstPluginEntries } from "./first-plugin.generated"',
        'import { secondPluginEntries } from "./second-plugin.generated"',
      ],
      registrationImports: [...CORE_REGISTRATION_IMPORTS, sharedRegistrationImport, sharedRegistrationImport],
      calls: [...CORE_CALLS, 'registerEntries(firstPluginEntries)', 'registerEntries(secondPluginEntries)'],
    })

    expectNoSyntaxErrors(content)
    expect(parseImports(content).filter((parsed) => parsed.names.includes('registerEntries'))).toHaveLength(1)
    expect(parseRegistrationCalls(content)).toEqual([
      ...CORE_CALLS,
      'registerEntries(firstPluginEntries)',
      'registerEntries(secondPluginEntries)',
    ])
  })

  it('emits a valid module with an empty body when nothing registers at all', () => {
    const content = renderBootstrapRegistrationsFile({ entryImports: [], registrationImports: [], calls: [] })

    expectNoSyntaxErrors(content)
    expect(isExportedVoidFunction(content)).toBe(true)
    expect(parseImports(content)).toEqual([])
    expect(parseRegistrationCalls(content)).toEqual([])
  })

  it('fails at generation time and names the statement when a plugin import is malformed', () => {
    expect(() =>
      renderBootstrapRegistrationsFile({
        entryImports: CORE_ENTRY_IMPORTS,
        registrationImports: [...CORE_REGISTRATION_IMPORTS, 'registerSomething from "./not-an-import"'],
        calls: CORE_CALLS,
      }),
    ).toThrow('Expected import declaration, received: registerSomething from "./not-an-import"')
  })

  it('fails when a plugin import uses a non-literal module specifier', () => {
    expect(() =>
      renderBootstrapRegistrationsFile({
        entryImports: CORE_ENTRY_IMPORTS,
        registrationImports: [...CORE_REGISTRATION_IMPORTS, 'import { registerSomething } from `./templated`'],
        calls: CORE_CALLS,
      }),
    ).toThrow('Unsupported import declaration: import { registerSomething } from `./templated`')
  })

  it('pins the emitted text so emitter changes surface as a reviewable diff', () => {
    expect(
      renderBootstrapRegistrationsFile({
        entryImports: CORE_ENTRY_IMPORTS,
        registrationImports: CORE_REGISTRATION_IMPORTS,
        calls: CORE_CALLS,
      }),
    ).toMatchSnapshot()
  })
})
