// Pure source emitter for src/backend/icons/lucideRegistry.generated.tsx.
// Kept side-effect free, and CommonJS so both build.mjs and the Jest suite can load it.

const {
  IndentationText,
  Project,
  QuoteKind,
  ScriptKind,
  StructureKind,
  VariableDeclarationKind,
} = require('ts-morph')

const GENERATED_FILE_NAME = 'lucideRegistry.generated.tsx'
const LUCIDE_MODULE_SPECIFIER = 'lucide-react'
const BANNER = `/* eslint-disable */
// AUTO-GENERATED by @open-mercato/ui build. Do not edit by hand.
// Generated from discovered icon string usages across the repo.

`

let sharedProject = null

function getProject() {
  if (!sharedProject) {
    sharedProject = new Project({
      useInMemoryFileSystem: true,
      manipulationSettings: {
        indentationText: IndentationText.TwoSpaces,
        quoteKind: QuoteKind.Single,
        useTrailingCommas: true,
      },
    })
  }

  return sharedProject
}

function sortResolvedIcons(resolvedIcons) {
  return [...resolvedIcons].sort((a, b) => a.kebab.localeCompare(b.kebab))
}

function collectUniqueExports(resolvedIcons) {
  return [...new Set(resolvedIcons.map((icon) => icon.exportName))].sort((a, b) => a.localeCompare(b))
}

function writeNamedImports(exportNames) {
  return (writer) => {
    writer.newLine()
    for (const name of exportNames) {
      writer.write(`${name},`)
      writer.newLine()
    }
  }
}

function writeRegistryLiteral(entries) {
  return (writer) => {
    if (entries.length === 0) {
      writer.write('{}')
      return
    }

    writer.write('{')
    writer.newLine()
    for (const icon of entries) {
      writer.write(`'${icon.kebab}': ${icon.exportName},`)
      writer.newLine()
    }
    writer.write('}')
  }
}

function assertNoSyntacticDiagnostics(project, sourceFile) {
  const diagnostics = project.getProgram().getSyntacticDiagnostics(sourceFile)
  if (diagnostics.length === 0) return

  const details = diagnostics
    .map((diagnostic) => `  line ${diagnostic.getLineNumber() ?? 0}: ${diagnostic.getMessageText()}`)
    .join('\n')
  throw new Error(`[internal] Generated ${GENERATED_FILE_NAME} is not syntactically valid:\n${details}`)
}

function normalizeSourceText(text) {
  const normalized = text.replace(/\r\n/g, '\n')
  return normalized.endsWith('\n') ? normalized : `${normalized}\n`
}

function buildLucideRegistrySource(resolvedIcons) {
  const entries = sortResolvedIcons(resolvedIcons)
  const uniqueExports = collectUniqueExports(entries)

  const project = getProject()
  const sourceFile = project.createSourceFile(GENERATED_FILE_NAME, '', {
    overwrite: true,
    scriptKind: ScriptKind.TSX,
  })

  sourceFile.addImportDeclaration({
    kind: StructureKind.ImportDeclaration,
    isTypeOnly: true,
    namedImports: [{ name: 'LucideIcon' }],
    moduleSpecifier: LUCIDE_MODULE_SPECIFIER,
  })

  if (uniqueExports.length > 0) {
    sourceFile.addImportDeclaration({
      kind: StructureKind.ImportDeclaration,
      namedImports: writeNamedImports(uniqueExports),
      moduleSpecifier: LUCIDE_MODULE_SPECIFIER,
    })
  }

  sourceFile.addVariableStatement({
    kind: StructureKind.VariableStatement,
    isExported: true,
    declarationKind: VariableDeclarationKind.Const,
    declarations: [
      {
        name: 'LUCIDE_ICON_REGISTRY',
        type: 'Record<string, LucideIcon>',
        initializer: writeRegistryLiteral(entries),
      },
    ],
  })

  sourceFile.formatText({ indentSize: 2, convertTabsToSpaces: true })
  sourceFile.insertText(0, BANNER)
  assertNoSyntacticDiagnostics(project, sourceFile)

  return normalizeSourceText(sourceFile.getFullText())
}

module.exports = { buildLucideRegistrySource }
