import type { GeneratorPlugin } from '@open-mercato/shared/modules/generators'

function buildReferenceIndexOutput({
  importSection,
  entriesLiteral,
}: {
  importSection: string
  entriesLiteral: string
}): string {
  return `// AUTO-GENERATED by mercato generate registry
import type { ModuleReferenceIndexEntry } from '@/modules/example/lib/module-reference-index'
${importSection ? `${importSection}\n` : ''}
export const moduleReferenceIndexEntries: ModuleReferenceIndexEntry[] = [
${entriesLiteral ? `  ${entriesLiteral}\n` : ''}]
`
}

export const generatorPlugins: GeneratorPlugin[] = [
  {
    id: 'example.reference-index',
    conventionFile: 'reference-index.ts',
    importPrefix: 'MODULE_REFERENCE_INDEX',
    configExpr: (importName: string, moduleId: string) =>
      `{ moduleId: '${moduleId}', references: (${importName}.default ?? ${importName}.moduleReferenceDeclarations ?? []) }`,
    outputFileName: 'example-reference-index.generated.ts',
    buildOutput: buildReferenceIndexOutput,
    bootstrapRegistration: {
      entriesExportName: 'moduleReferenceIndexEntries',
      registrationImports: [
        `import { registerModuleReferenceIndexEntries } from '@/modules/example/lib/module-reference-index'`,
      ],
      buildCall: (entriesExportName: string) =>
        `registerModuleReferenceIndexEntries(${entriesExportName})`,
    },
  },
]

export default generatorPlugins
