import fs from 'node:fs'
import path from 'node:path'
import { StructureKind, VariableDeclarationKind } from 'ts-morph'
import type { PackageResolver } from '../resolver'
import { MODULE_CODE_EXTENSIONS } from './scanner'
import {
  toVar,
  type GeneratorResult,
  createGeneratorResult,
  writeGeneratedFile,
} from '../utils'
import {
  addAutoGeneratedComment,
  addImportSpec,
  arrayLiteral,
  createGeneratedSourceFile,
  getSourceText,
  identifier,
  methodCall,
  parenthesized,
} from './ast'

export interface ModuleDiOptions {
  resolver: PackageResolver
  quiet?: boolean
}

export async function generateModuleDi(options: ModuleDiOptions): Promise<GeneratorResult> {
  const { resolver, quiet = false } = options
  const result = createGeneratorResult()

  const outputDir = resolver.getOutputDir()
  const outFile = path.join(outputDir, 'di.generated.ts')
  const checksumFile = path.join(outputDir, 'di.generated.checksum')

  const mods = resolver.loadEnabledModules()
  const imports: Array<{ name: string; moduleSpecifier: string }> = []
  const registrars: string[] = []
  let i = 0

  for (const entry of mods) {
    const modId = entry.id
    const roots = resolver.getModulePaths(entry)
    const imp = resolver.getModuleImportBase(entry)
    const isAppModule = entry.from === '@app'

    const useApp = resolveModuleConventionFile(roots.appBase, 'di')
    const usePkg = resolveModuleConventionFile(roots.pkgBase, 'di')
    const importName = `D_${toVar(modId)}_${i++}`

    if (useApp) {
      warnIfDiMissingRegisterExport(findModuleConventionFilePath(roots.appBase, 'di'), quiet)
      // For @app modules, use relative path to work in both Next.js and Node.js CLI context
      // From .mercato/generated/, go up two levels (../..) to reach the app root, then into src/modules/
      const importPath = isAppModule ? `../../src/modules/${modId}/di` : `${imp.appBase}/di`
      imports.push({ name: importName, moduleSpecifier: importPath })
      registrars.push(`${importName}.register`)
    } else if (usePkg) {
      warnIfDiMissingRegisterExport(findModuleConventionFilePath(roots.pkgBase, 'di'), quiet)
      imports.push({ name: importName, moduleSpecifier: `${imp.pkgBase}/di` })
      registrars.push(`${importName}.register`)
    }
  }

  const sourceFile = createGeneratedSourceFile('di.generated.ts')
  addAutoGeneratedComment(sourceFile, 'di')
  imports.forEach((entry) => {
    addImportSpec(sourceFile, {
      kind: StructureKind.ImportDeclaration,
      namespaceImport: entry.name,
      moduleSpecifier: entry.moduleSpecifier,
    })
  })
  sourceFile.addVariableStatement({
    declarationKind: VariableDeclarationKind.Const,
    declarations: [
      {
        name: 'diRegistrars',
        type: '(((c: any) => void) | undefined)[]',
        initializer: methodCall(
          parenthesized(arrayLiteral(registrars, (currentWriter, registrar) => identifier(registrar)(currentWriter))),
          'filter',
          [identifier('Boolean')],
        ),
      },
    ],
  })
  sourceFile.addExportDeclaration({
    namedExports: ['diRegistrars'],
  })
  sourceFile.addExportAssignment({
    isExportEquals: false,
    expression: 'diRegistrars',
  })
  const output = getSourceText(sourceFile)

  writeGeneratedFile({
    outFile,
    checksumFile,
    content: output,
    structureChecksum: '',
    result,
    quiet,
  })

  return result
}

function resolveModuleConventionFile(baseDir: string, basename: string): boolean {
  return MODULE_CODE_EXTENSIONS.some((extension) => fs.existsSync(path.join(baseDir, `${basename}${extension}`)))
}

function findModuleConventionFilePath(baseDir: string, basename: string): string | null {
  for (const extension of MODULE_CODE_EXTENSIONS) {
    const candidate = path.join(baseDir, `${basename}${extension}`)
    if (fs.existsSync(candidate)) return candidate
  }
  return null
}

/**
 * Warns when a discovered `di.ts` exports no `register`.
 *
 * The generated registrar list is built from `<import>.register` for every module that has a
 * `di` file. A differently named export makes that entry `undefined`, so the module's DI
 * registrations silently never run and its services surface as missing at request time
 * instead of at generation time.
 */
export function warnIfDiMissingRegisterExport(diPath: string | null, quiet = false): void {
  if (!diPath || quiet) return
  let source = ''
  try {
    source = fs.readFileSync(diPath, 'utf8')
  } catch {
    return
  }
  const exportsRegister = /export\s+(async\s+)?function\s+register\b/.test(source)
    || /export\s+(const|let|var)\s+register\b/.test(source)
    || /export\s*\{[^}]*\bregister\b[^}]*\}/.test(source)
  if (exportsRegister) return
  console.warn(
    `[generate] ⚠ di.ts exports no 'register' — this module's DI registrations will never run: ${diPath}`,
  )
}
