export type RouteManifestShardKind = 'api' | 'backend'

export type RouteManifestShardEntry = {
  path: string
  declaration: string
  imports?: string[]
}

export type RouteManifestShardOutput = {
  fileName: string
  content: string
}

type IndexedRouteManifestShardEntry = RouteManifestShardEntry & {
  order: number
}

const DYNAMIC_SHARD_KEY = '__dynamic'
const ROOT_SHARD_KEY = '__root'

function normalizeRoutePath(kind: RouteManifestShardKind, pathname: string): string[] {
  const segments = pathname.split('?')[0].split('/').filter(Boolean)
  if (kind === 'backend' && segments[0]?.toLowerCase() === 'backend') {
    segments.shift()
  }
  return segments
}

export function getRouteManifestShardKey(kind: RouteManifestShardKind, pathname: string): string {
  const firstSegment = normalizeRoutePath(kind, pathname)[0]
  if (!firstSegment) return ROOT_SHARD_KEY
  if (
    firstSegment.startsWith('[')
    || firstSegment.startsWith(':')
    || firstSegment === '*'
  ) {
    return DYNAMIC_SHARD_KEY
  }
  return firstSegment.toLowerCase()
}

function renderArray(entries: RouteManifestShardEntry[]): string {
  if (entries.length === 0) return '[]'
  return `[\n${entries.map((entry) => `  ${entry.declaration}`).join(',\n')}\n]`
}

function uniqueImports(entries: RouteManifestShardEntry[]): string[] {
  return Array.from(new Set(entries.flatMap((entry) => entry.imports ?? [])))
}

function shardStem(kind: RouteManifestShardKind, index: number, key: string): string {
  const safeKey = key.replace(/[^a-zA-Z0-9_-]/g, '_')
  return `${kind}-route-shard.${String(index).padStart(3, '0')}.${safeKey}.generated`
}

function renderShardFile(kind: RouteManifestShardKind, entries: IndexedRouteManifestShardEntry[]): string {
  const typeName = kind === 'api' ? 'ApiRouteManifestEntry' : 'BackendRouteManifestEntry'
  const helperImport = kind === 'backend' ? 'resolvePageRouteMetadata, ' : ''
  const imports = uniqueImports(entries)
  return `// AUTO-GENERATED by mercato generate registry (request-scoped route shard)\nimport { ${helperImport}type ${typeName} } from '@open-mercato/shared/modules/registry'\n${imports.length ? `${imports.join('\n')}\n` : ''}\nexport const routes: ${typeName}[] = ${renderArray(entries)}\nexport const routeOrders = [${entries.map((entry) => entry.order).join(', ')}]\n\nexport default routes\n`
}

function renderLoaderFile(
  kind: RouteManifestShardKind,
  shards: Array<{ key: string; stem: string; orders: number[] }>,
): string {
  const isApi = kind === 'api'
  const typeName = kind === 'api' ? 'ApiRouteManifestEntry' : 'BackendRouteManifestEntry'
  const functionName = kind === 'api' ? 'loadApiRouteManifestShard' : 'loadBackendRouteManifestShard'
  const ordinalFunctionName = isApi ? 'loadApiRouteManifestByOrdinal' : 'loadBackendRouteManifestByOrdinal'
  const facadeExportName = isApi ? 'apiRouteFacades' : 'backendRouteFacades'
  const metadataExportName = isApi ? 'apiRouteMetadata' : 'backendRouteMetadata'
  const metadataFileName = isApi ? 'api-route-metadata.generated' : 'backend-route-metadata.generated'
  const shardCases = shards
    .map(({ key, stem }) => `    case ${JSON.stringify(key)}:\n      return import('./${stem}').then((entry) => ({ routes: entry.routes, routeOrders: entry.routeOrders }))`)
    .join('\n')
  const hasDynamicShard = shards.some(({ key }) => key === DYNAMIC_SHARD_KEY)
  const routeShardKeys: string[] = []
  for (const shard of shards) {
    for (const order of shard.orders) routeShardKeys[order] = shard.key
  }
  const prefixNormalization = kind === 'backend'
    ? `  if (segments[0]?.toLowerCase() === 'backend') segments.shift()\n`
    : ''
  const loadDynamic = hasDynamicShard
    ? `  const dynamicShard = await loadShard(${JSON.stringify(DYNAMIC_SHARD_KEY)})\n`
    : `  const dynamicShard: LoadedRouteShard = EMPTY_SHARD\n`

  return `// AUTO-GENERATED by mercato generate registry (request-scoped route loader)\nimport type { ${typeName} } from '@open-mercato/shared/modules/registry'\nimport { ${metadataExportName} } from './${metadataFileName}'\n\ntype LoadedRouteShard = { routes: ${typeName}[]; routeOrders: number[] }\nconst EMPTY_SHARD: LoadedRouteShard = { routes: [], routeOrders: [] }\nconst ROUTE_SHARD_KEYS = ${JSON.stringify(routeShardKeys)}\n\nfunction resolveShardKey(pathname: string): string {\n  const segments = pathname.split('?')[0].split('/').filter(Boolean)\n${prefixNormalization}  return segments[0]?.toLowerCase() ?? ${JSON.stringify(ROOT_SHARD_KEY)}\n}\n\nasync function loadShard(key: string): Promise<LoadedRouteShard> {\n  switch (key) {\n${shardCases ? `${shardCases}\n` : ''}    default:\n      return EMPTY_SHARD\n  }\n}\n\nexport async function ${ordinalFunctionName}(ordinal: number): Promise<${typeName}> {\n  const shardKey = ROUTE_SHARD_KEYS[ordinal]\n  if (shardKey === undefined) throw new Error('Unknown generated route manifest ordinal: ' + ordinal)\n  const shard = await loadShard(shardKey)\n  const index = shard.routeOrders.indexOf(ordinal)\n  if (index < 0 || !shard.routes[index]) throw new Error('Generated route manifest ordinal is missing from its shard: ' + ordinal)\n  return shard.routes[index]\n}\n\nexport const ${facadeExportName}: ${typeName}[] = ${metadataExportName}.map((metadata, ordinal) => ({\n  ...metadata,\n  load: async () => {\n    const route = await ${ordinalFunctionName}(ordinal)\n    return route.load()\n  },\n}))\n\nexport async function ${functionName}(pathname: string): Promise<${typeName}[]> {\n  const exactShard = await loadShard(resolveShardKey(pathname))\n${loadDynamic}  return [\n    ...exactShard.routes.map((route, index) => ({ route, order: exactShard.routeOrders[index] })),\n    ...dynamicShard.routes.map((route, index) => ({ route, order: dynamicShard.routeOrders[index] })),\n  ].sort((a, b) => a.order - b.order).map(({ route }) => route)\n}\n`
}

export function renderRouteManifestShardOutputs(
  kind: RouteManifestShardKind,
  entries: RouteManifestShardEntry[],
): RouteManifestShardOutput[] {
  const grouped = new Map<string, IndexedRouteManifestShardEntry[]>()
  for (const [order, entry] of entries.entries()) {
    const key = getRouteManifestShardKey(kind, entry.path)
    const existing = grouped.get(key)
    const indexedEntry = { ...entry, order }
    if (existing) existing.push(indexedEntry)
    else grouped.set(key, [indexedEntry])
  }

  const sortedGroups = Array.from(grouped.entries()).sort(([a], [b]) => a.localeCompare(b))
  const shards = sortedGroups.map(([key, shardEntries], index) => {
    const stem = shardStem(kind, index, key)
    return {
      key,
      stem,
      orders: shardEntries.map((entry) => entry.order),
      output: {
        fileName: `${stem}.ts`,
        content: renderShardFile(kind, shardEntries),
      },
    }
  })
  const loaderFileName = kind === 'api'
    ? 'api-route-shards.generated.ts'
    : 'backend-route-shards.generated.ts'

  return [
    ...shards.map(({ output }) => output),
    {
      fileName: loaderFileName,
      content: renderLoaderFile(kind, shards),
    },
  ]
}

export function renderRouteMetadataOutput(
  kind: RouteManifestShardKind,
  entries: RouteManifestShardEntry[],
): RouteManifestShardOutput {
  const isApi = kind === 'api'
  const manifestType = isApi ? 'ApiRouteManifestEntry' : 'BackendRouteManifestEntry'
  const metadataType = isApi ? 'ApiRouteMetadataEntry' : 'BackendRouteMetadataEntry'
  const exportName = isApi ? 'apiRouteMetadata' : 'backendRouteMetadata'
  const fileName = isApi ? 'api-route-metadata.generated.ts' : 'backend-route-metadata.generated.ts'
  const helperImport = isApi ? '' : 'resolvePageRouteMetadata, '
  const imports = uniqueImports(entries)
  const content = `// AUTO-GENERATED by mercato generate registry (route metadata without component loaders)\nimport { ${helperImport}type ${manifestType} } from '@open-mercato/shared/modules/registry'\n${imports.length ? `${imports.join('\n')}\n` : ''}\nexport type ${metadataType} = Omit<${manifestType}, 'load'>\n\nexport const ${exportName}: ${metadataType}[] = ${renderArray(entries)}\n\nexport default ${exportName}\n`
  return { fileName, content }
}

export const routeManifestShardFilePattern = /^(?:api|backend)-route-shard\..+\.generated\.(?:ts|checksum)$/
