const MEBIBYTE = 1024 * 1024

export const DOCUMENTS_MAX_VERSIONS_PER_DOCUMENT = 100
export const DOCUMENTS_MAX_VERSION_STORAGE_BYTES = 256 * MEBIBYTE
export const DOCUMENTS_VERSION_LIST_PAGE_SIZE = DOCUMENTS_MAX_VERSIONS_PER_DOCUMENT
export const DOCUMENTS_MAX_COMMENTS_PER_DOCUMENT = 500
export const DOCUMENTS_COMMENT_LIST_PAGE_SIZE = 100
