import type { GeneratorPlugin } from '@open-mercato/shared/modules/generators'

function buildSourcesOutput({ importSection, entriesLiteral }: { importSection: string; entriesLiteral: string }): string {
  return `// AUTO-GENERATED by mercato generate registry
import type { WebhookSourceConfig } from '@open-mercato/shared/lib/webhooks'
${importSection ? `${importSection}\n` : ''}type WebhookSourceModuleEntry = { moduleId: string; sources: WebhookSourceConfig[] }

export const webhookSourceEntries: WebhookSourceModuleEntry[] = [
${entriesLiteral ? `  ${entriesLiteral}\n` : ''}]
`
}

function buildHandlersOutput({ importSection, entriesLiteral }: { importSection: string; entriesLiteral: string }): string {
  return `// AUTO-GENERATED by mercato generate registry
import type { WebhookHandlerRegistryEntry } from '@open-mercato/shared/lib/webhooks'
${importSection ? `${importSection}\n` : ''}type WebhookHandlerModuleEntry = { moduleId: string; handlers: WebhookHandlerRegistryEntry[] }

export const webhookHandlerEntries: WebhookHandlerModuleEntry[] = [
${entriesLiteral ? `  ${entriesLiteral}\n` : ''}]
`
}

const sourcesPlugin: GeneratorPlugin = {
  id: 'webhooks.sources',
  conventionFile: 'webhook-sources.ts',
  importPrefix: 'WEBHOOK_SOURCES',
  configExpr: (importName: string, moduleId: string) =>
    `{ moduleId: '${moduleId}', sources: ((${importName}.default ?? ${importName}.webhookSources ?? []) as WebhookSourceConfig[]) }`,
  outputFileName: 'webhook-sources.generated.ts',
  buildOutput: buildSourcesOutput,
  bootstrapRegistration: {
    entriesExportName: 'webhookSourceEntries',
    registrationImports: [
      `import { registerWebhookSourceEntries } from '@open-mercato/webhooks/modules/webhooks/lib/module-webhook-registry'`,
    ],
    buildCall: (name: string) => `registerWebhookSourceEntries(${name})`,
  },
}

const handlersPlugin: GeneratorPlugin = {
  id: 'webhooks.handlers',
  conventionFile: 'webhook-handlers.ts',
  importPrefix: 'WEBHOOK_HANDLERS',
  configExpr: (importName: string, moduleId: string) =>
    `{ moduleId: '${moduleId}', handlers: ((${importName}.default ?? ${importName}.webhookHandlers ?? []) as WebhookHandlerRegistryEntry[]) }`,
  outputFileName: 'webhook-handlers.generated.ts',
  buildOutput: buildHandlersOutput,
  bootstrapRegistration: {
    entriesExportName: 'webhookHandlerEntries',
    registrationImports: [
      `import { registerWebhookHandlerEntries } from '@open-mercato/webhooks/modules/webhooks/lib/module-webhook-registry'`,
    ],
    buildCall: (name: string) => `registerWebhookHandlerEntries(${name})`,
  },
}

export const generatorPlugins: GeneratorPlugin[] = [sourcesPlugin, handlersPlugin]
