import { z } from 'zod'
import { buildOpenApiDocument } from '../generator'
import type { Module, ModuleApiRouteFile } from '../../../modules/registry'
import type { OpenApiMethodDoc } from '../types'

type ResponseEntry = {
  description?: string
  content?: Record<string, { schema?: { properties?: Record<string, unknown> } }>
  'x-autoGenerated'?: boolean
}

type Operation = { responses: Record<string, ResponseEntry> }

const errorSchema = z.object({ error: z.string(), code: z.string() })
const routePath = '/example/records'
const guardedMetadata = { GET: { requireAuth: true, requireFeatures: ['example.records.view'] } }

function makeModule(methodDoc: OpenApiMethodDoc, metadata: ModuleApiRouteFile['metadata']): Module {
  const api: ModuleApiRouteFile = {
    path: routePath,
    metadata,
    handlers: { GET: async () => new Response(null) },
    docs: { tag: 'Example', methods: { GET: methodDoc } },
  }
  return { id: 'example', apis: [api] }
}

function getOperationWithMetadata(
  methodDoc: OpenApiMethodDoc,
  metadata: ModuleApiRouteFile['metadata']
): Operation {
  const doc = buildOpenApiDocument([makeModule(methodDoc, metadata)])
  return doc.paths[routePath]?.get as Operation
}

function getOperation(methodDoc: OpenApiMethodDoc): Operation {
  return getOperationWithMetadata(methodDoc, guardedMetadata)
}

function jsonSchemaProperties(entry: ResponseEntry): Record<string, unknown> | undefined {
  return entry.content?.['application/json']?.schema?.properties
}

describe('buildResponses precedence between declared and inferred responses', () => {
  it('keeps a 403 declared through responses instead of the requireFeatures default', () => {
    const operation = getOperation({
      responses: [
        { status: 200, description: 'Records', schema: z.object({ items: z.array(z.string()) }) },
        { status: 403, description: 'Record is outside the active scope', schema: errorSchema },
      ],
    })

    expect(operation.responses['403'].description).toBe('Record is outside the active scope')
    expect(operation.responses['403']['x-autoGenerated']).toBeUndefined()
    expect(jsonSchemaProperties(operation.responses['403'])?.code).toBeDefined()
  })

  it('keeps a 403 declared through errors instead of the requireFeatures default', () => {
    const operation = getOperation({
      responses: [{ status: 200, description: 'Records' }],
      errors: [{ status: 403, description: 'Record is outside the active scope', schema: errorSchema }],
    })

    expect(operation.responses['403'].description).toBe('Record is outside the active scope')
    expect(operation.responses['403']['x-autoGenerated']).toBeUndefined()
    expect(jsonSchemaProperties(operation.responses['403'])?.code).toBeDefined()
  })

  it('keeps a 401 declared through errors instead of the requireAuth default', () => {
    const operation = getOperation({
      responses: [{ status: 200, description: 'Records' }],
      errors: [{ status: 401, description: 'Session token expired', schema: errorSchema }],
    })

    expect(operation.responses['401'].description).toBe('Session token expired')
    expect(operation.responses['401']['x-autoGenerated']).toBeUndefined()
  })

  it('keeps a 401 declared through responses instead of the requireAuth default', () => {
    const operation = getOperation({
      responses: [
        { status: 200, description: 'Records' },
        { status: 401, description: 'Session token expired', schema: errorSchema },
      ],
    })

    expect(operation.responses['401'].description).toBe('Session token expired')
    expect(operation.responses['401']['x-autoGenerated']).toBeUndefined()
  })

  it('emits both inferred entries when the route documents neither status', () => {
    const operation = getOperation({
      responses: [{ status: 200, description: 'Records' }],
      errors: [{ status: 404, description: 'Not found', schema: errorSchema }],
    })

    expect(operation.responses['401'].description).toBe('Unauthorized')
    expect(operation.responses['401']['x-autoGenerated']).toBe(true)
    expect(operation.responses['403'].description).toBe('Forbidden – missing required features')
    expect(operation.responses['403']['x-autoGenerated']).toBe(true)
    expect(operation.responses['404'].description).toBe('Not found')
    expect(operation.responses['404']['x-autoGenerated']).toBeUndefined()
  })

  it('mixes a declared 403 with the inferred 401 on the same operation', () => {
    const operation = getOperation({
      responses: [{ status: 200, description: 'Records' }],
      errors: [{ status: 403, description: 'Record is outside the active scope', schema: errorSchema }],
    })

    expect(operation.responses['403']['x-autoGenerated']).toBeUndefined()
    expect(operation.responses['401']['x-autoGenerated']).toBe(true)
  })

  it('still synthesises the success response when the route declares only errors', () => {
    const operation = getOperation({
      errors: [{ status: 403, description: 'Record is outside the active scope', schema: errorSchema }],
    })

    expect(operation.responses['200'].description).toBe('Success response')
    expect(operation.responses['403'].description).toBe('Record is outside the active scope')
  })

  it('infers nothing when the route declares no auth or feature metadata', () => {
    const operation = getOperationWithMetadata({ responses: [{ status: 200, description: 'Records' }] }, undefined)

    expect(Object.keys(operation.responses)).toEqual(['200'])
  })

  it('infers only the 401 when the route requires auth without features', () => {
    const operation = getOperationWithMetadata({ responses: [{ status: 200, description: 'Records' }] }, {
      GET: { requireAuth: true },
    })

    expect(operation.responses['401']['x-autoGenerated']).toBe(true)
    expect(operation.responses['403']).toBeUndefined()
  })

  it('pins the documented last-wins behaviour when responses and errors collide on one status', () => {
    const operation = getOperation({
      responses: [
        { status: 200, description: 'Records' },
        { status: 409, description: 'Declared through responses', schema: errorSchema },
      ],
      errors: [{ status: 409, description: 'Declared through errors', schema: errorSchema }],
    })

    expect(operation.responses['409'].description).toBe('Declared through errors')
  })
})
