import type { GeneratorPlugin } from '@open-mercato/shared/modules/generators'

function buildDeliveryStrategiesOutput({
  importSection,
  entriesLiteral,
}: {
  importSection: string
  entriesLiteral: string
}): string {
  return `// AUTO-GENERATED by mercato generate registry
${importSection ? `${importSection}\n` : ''}type NotificationDeliveryStrategyEntry = { moduleId: string; strategies: unknown[] }

export const notificationDeliveryStrategyEntries: NotificationDeliveryStrategyEntry[] = [
${entriesLiteral ? `  ${entriesLiteral}\n` : ''}]
`
}

/**
 * Lets any module contribute notification delivery strategies by exporting
 * `notifications.delivery-strategies.ts` (`export const deliveryStrategies = [...]`). The generator
 * aggregates them and wires a bootstrap registration call, so the strategy registry is populated at
 * boot without `bootstrap.ts` knowing about individual modules. Mirrors the security MFA-provider plugin.
 */
const deliveryStrategiesPlugin: GeneratorPlugin = {
  id: 'notifications.delivery-strategies',
  conventionFile: 'notifications.delivery-strategies.ts',
  importPrefix: 'NOTIFICATIONS_DELIVERY_STRATEGIES',
  configExpr: (importName: string, moduleId: string) =>
    `{ moduleId: '${moduleId}', strategies: ((${importName}.default ?? ${importName}.deliveryStrategies ?? []) as unknown[]) }`,
  outputFileName: 'notifications-delivery-strategies.generated.ts',
  buildOutput: buildDeliveryStrategiesOutput,
  bootstrapRegistration: {
    entriesExportName: 'notificationDeliveryStrategyEntries',
    registrationImports: [
      `import { registerNotificationDeliveryStrategyEntries } from '@open-mercato/core/modules/notifications/lib/delivery-strategies-registry'`,
    ],
    buildCall: (name: string) => `registerNotificationDeliveryStrategyEntries(${name})`,
  },
}

function buildChannelsOutput({
  importSection,
  entriesLiteral,
}: {
  importSection: string
  entriesLiteral: string
}): string {
  return `// AUTO-GENERATED by mercato generate registry
${importSection ? `${importSection}\n` : ''}type NotificationChannelEntry = { moduleId: string; channels: unknown[] }

export const notificationChannelEntries: NotificationChannelEntry[] = [
${entriesLiteral ? `  ${entriesLiteral}\n` : ''}]
`
}

/**
 * Lets any module contribute notification channels (metadata for the preferences UI + the
 * `/api/notifications/channels` endpoint) by exporting `notification-channels.ts`
 * (`export const notificationChannels = [...]`). The generator aggregates them and wires a bootstrap
 * registration call, so the channel catalogue is populated at boot without `bootstrap.ts` knowing about
 * individual modules. Mirrors the delivery-strategies plugin.
 */
const channelsPlugin: GeneratorPlugin = {
  id: 'notifications.channels',
  conventionFile: 'notification-channels.ts',
  importPrefix: 'NOTIFICATION_CHANNELS',
  configExpr: (importName: string, moduleId: string) =>
    `{ moduleId: '${moduleId}', channels: ((${importName}.default ?? ${importName}.notificationChannels ?? []) as unknown[]) }`,
  outputFileName: 'notification-channels.generated.ts',
  buildOutput: buildChannelsOutput,
  bootstrapRegistration: {
    entriesExportName: 'notificationChannelEntries',
    registrationImports: [
      `import { registerNotificationChannelEntries } from '@open-mercato/core/modules/notifications/lib/notification-channel-registry'`,
    ],
    buildCall: (name: string) => `registerNotificationChannelEntries(${name})`,
  },
}

export const generatorPlugins: GeneratorPlugin[] = [deliveryStrategiesPlugin, channelsPlugin]

export default generatorPlugins
